"""
Professional PDF Report Generator with Branding, QR Code, and Multi-language Support
"""
import io
import uuid
from datetime import datetime
import qrcode
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.utils import ImageReader


def generate_pdf_report(report_data, filename, language="en"):
    """
    Generate professional PDF report with all branding elements
    
    Args:
        report_data: dict containing disease and ai_report data
        filename: output PDF file path
        language: "en" for English or "hi" for Hindi
    
    Returns:
        str: Unique report ID
    """
    
    c = canvas.Canvas(filename, pagesize=A4)
    width, height = A4
    
    # Generate unique Report ID
    report_id = str(uuid.uuid4())[:8].upper()
    scan_date = datetime.now().strftime("%d %b %Y, %H:%M")
    
    # Multi-language translations
    translations = {
        "en": {
            "title": "FasalRakshak - Plant Disease Report",
            "report_id": "Report ID",
            "scan_date": "Scan Date",
            "disease": "Disease Detected",
            "crop": "Crop Name",
            "severity": "Severity",
            "affected_area": "Affected Area",
            "recovery": "Recovery Timeline",
            "symptoms": "Observed Symptoms",
            "treatment": "Immediate Treatment",
            "prevention": "Prevention Measures",
            "generated_by": "Generated by FasalRakshak",
            "organic": "Organic Treatment",
            "chemical": "Chemical Treatment",
            "fertilizer": "Fertilizer Advice",
            "description": "Disease Description"
        },
        "hi": {
            "title": "फसलरक्षक - पौधे रोग रिपोर्ट",
            "report_id": "रिपोर्ट आईडी",
            "scan_date": "स्कैन तारीख",
            "disease": "रोग का पता चला",
            "crop": "फसल का नाम",
            "severity": "गंभीरता",
            "affected_area": "प्रभावित क्षेत्र",
            "recovery": "ठीक होने का समय",
            "symptoms": "लक्षण",
            "treatment": "तत्काल उपचार",
            "prevention": "रोकथाम",
            "generated_by": "फसलरक्षक द्वारा निर्मित",
            "organic": "जैविक उपचार",
            "chemical": "रासायनिक उपचार",
            "fertilizer": "उर्वरक सलाह",
            "description": "रोग विवरण"
        }
    }
    
    t = translations.get(language, translations["en"])
    
    # Generate QR Code
    qr = qrcode.QRCode(version=1, box_size=10, border=2)
    qr_url = f"https://fasalrakshak.com/report/{report_id}"
    qr.add_data(qr_url)
    qr.make(fit=True)
    qr_img = qr.make_image(fill_color="black", back_color="white")
    qr_buffer = io.BytesIO()
    qr_img.save(qr_buffer, format='PNG')
    qr_buffer.seek(0)
    
    def draw_watermark():
        """Draw diagonal transparent watermark across page"""
        c.saveState()
        c.setFont("Helvetica-Bold", 60)
        c.setFillColorRGB(0.9, 0.9, 0.9, alpha=0.15)
        c.translate(width / 2, height / 2)
        c.rotate(45)
        c.drawCentredString(0, 0, "FasalRakshak")
        c.restoreState()
    
    def draw_header():
        """Draw professional header with logo and metadata"""
        # Logo (text-based emoji logo)
        c.setFont("Helvetica-Bold", 20)
        c.setFillColorRGB(0.2, 0.6, 0.2)
        c.drawString(40, height - 50, "🌾 FasalRakshak")
        
        # Report metadata on right side
        c.setFont("Helvetica", 10)
        c.setFillColorRGB(0, 0, 0)
        c.drawRightString(width - 40, height - 40, f"{t['report_id']}: {report_id}")
        c.drawRightString(width - 40, height - 55, f"{t['scan_date']}: {scan_date}")
        
        # Title
        c.setFont("Helvetica-Bold", 16)
        c.setFillColorRGB(0.2, 0.6, 0.2)
        c.drawCentredString(width / 2, height - 90, t["title"])
        
        # Green separator line
        c.setStrokeColorRGB(0.2, 0.6, 0.2)
        c.setLineWidth(2)
        c.line(40, height - 100, width - 40, height - 100)
    
    def draw_footer(page_num):
        """Draw footer with generated by text and QR code"""
        c.setFont("Helvetica", 9)
        c.setFillColorRGB(0.5, 0.5, 0.5)
        c.drawCentredString(width / 2, 40, f"{t['generated_by']} | {t['report_id']}: {report_id}")
        
        # QR Code in bottom right corner
        c.drawImage(ImageReader(qr_buffer), width - 100, 20, width=70, height=70)
        qr_buffer.seek(0)  # Reset buffer position for next page
    
    def wrap_text(text, max_width, font_name="Helvetica", font_size=11):
        """Wrap text to fit within max_width"""
        words = str(text).split()
        lines = []
        current_line = ""
        
        for word in words:
            test_line = f"{current_line} {word}".strip()
            if c.stringWidth(test_line, font_name, font_size) <= max_width:
                current_line = test_line
            else:
                if current_line:
                    lines.append(current_line)
                current_line = word
        
        if current_line:
            lines.append(current_line)
        
        return lines
    
    # Start first page
    draw_watermark()
    draw_header()
    
    y = height - 130
    c.setFont("Helvetica", 12)
    
    def draw_section(title, content, is_list=False):
        """Draw a section with title and content"""
        nonlocal y
        
        # Check if need new page
        if y < 150:
            draw_footer(1)
            c.showPage()
            draw_watermark()
            draw_header()
            y = height - 130
        
        # Section title
        c.setFont("Helvetica-Bold", 14)
        c.setFillColorRGB(0.2, 0.6, 0.2)
        c.drawString(40, y, title)
        y -= 20
        
        # Section content
        c.setFont("Helvetica", 11)
        c.setFillColorRGB(0, 0, 0)
        
        if is_list and isinstance(content, list):
            # List items
            for item in content:
                if y < 150:
                    draw_footer(1)
                    c.showPage()
                    draw_watermark()
                    draw_header()
                    y = height - 130
                
                c.drawString(60, y, f"• {item}")
                y -= 18
        else:
            # Regular text with wrapping
            text = str(content)
            max_width = width - 100
            lines = wrap_text(text, max_width)
            
            for line in lines:
                if y < 150:
                    draw_footer(1)
                    c.showPage()
                    draw_watermark()
                    draw_header()
                    y = height - 130
                
                c.drawString(60, y, line)
                y -= 18
        
        y -= 10  # Extra spacing after section
    
    # Extract data from report
    ai_report = report_data.get("ai_report", {})
    disease = report_data.get("disease", "Unknown")
    
    # Draw all sections in order
    draw_section(t["disease"], disease)
    
    if ai_report:
        # Crop name
        crop = ai_report.get("crop_name", disease.split("___")[0] if "___" in disease else "Unknown")
        draw_section(t["crop"], crop)
        
        # Disease description
        if ai_report.get("disease_description"):
            draw_section(t["description"], ai_report.get("disease_description"))
        
        # Severity and affected area
        draw_section(t["severity"], ai_report.get("severity", "N/A"))
        draw_section(t["affected_area"], ai_report.get("affected_area", "N/A"))
        draw_section(t["recovery"], ai_report.get("recovery_timeline", "N/A"))
        
        # Symptoms (list)
        symptoms = ai_report.get("symptoms", [])
        if symptoms:
            draw_section(t["symptoms"], symptoms, is_list=True)
        
        # Treatment (list)
        treatment = ai_report.get("treatment", [])
        if treatment:
            draw_section(t["treatment"], treatment, is_list=True)
        
        # Organic treatment (list)
        organic = ai_report.get("organic_treatment", [])
        if organic:
            draw_section(t["organic"], organic, is_list=True)
        
        # Chemical treatment (special formatting)
        chem = ai_report.get("chemical_treatment", {})
        if isinstance(chem, dict) and chem.get("name"):
            chem_text = f"{chem.get('name')} - Dosage: {chem.get('dosage', 'N/A')}, Application: {chem.get('application_method', 'N/A')}"
            draw_section(t["chemical"], chem_text)
        
        # Fertilizer advice
        if ai_report.get("fertilizer_advice"):
            draw_section(t["fertilizer"], ai_report.get("fertilizer_advice"))
        
        # Prevention tips (list)
        prevention = ai_report.get("prevention_tips", ai_report.get("prevention", []))
        if prevention:
            draw_section(t["prevention"], prevention, is_list=True)
    
    # Draw final footer
    draw_footer(1)
    
    # Save PDF
    c.save()
    
    print(f"✅ PDF generated: {filename}")
    print(f"   Report ID: {report_id}")
    print(f"   Language: {language}")
    
    return report_id
