/**
 * Multilingual Translation System
 * Supports: English (en), Hindi (hi)
 */

export type Language = "en" | "hi"

/**
 * Translation dictionary
 * IMPORTANT:
 * - Every key MUST exist in both languages
 * - Use t("key") everywhere in UI
 */
export const translations = {
  en: {
    // Navigation
    home: "Home",
    scan: "Scan",
    dashboard: "Dashboard",
    analytics: "Analytics",
    aiAssistant: "AI Assistant",
    login: "Login",
    logout: "Logout",
    signup: "Sign Up",

    // Home Page
    welcomeTitle: "Protect Your Crops with AI",
    welcomeSubtitle: "Advanced plant disease detection using deep learning",
    startScanning: "Start Scanning",
    aiAssistantDescription: "Get instant answers about plant diseases, treatments, farming techniques, and more",
    askAIPlantExpert: "Ask Our AI Plant Expert",
    chatWithAIAssistant: "Chat with AI Assistant",
    plantDiseaseHelp: "Plant Disease Help",
    farmingTechniques: "Farming Techniques",
    irrigationTips: "Irrigation Tips",
    fertilizerGuide: "Fertilizer Guide",
    takeClearPhoto: "Take a clear photo of the plant leaf or crop for accurate disease detection",
    uploadImage: "Upload Image",
    clickToBrowse: "Click to browse or drag & drop",
    chooseFile: "Choose File",
    takePhoto: "Take Photo",
    captureLivePhoto: "Capture a live photo",
    openCamera: "Open Camera",
    cameraActive: "Camera Active",
    scanningWithAI: "Scanning with AI...",
    scanForDisease: "Scan for Disease",
    analyzingPlantImage: "Analyzing Plant Image...",
    aiModelProcessing: "AI model processing deep learning analysis",

    // Results Page
    resultsTitle: "Scan Results",
    diseaseDetected: "Disease Detected",
    cropName: "Crop Name",
    confidence: "Confidence",
    severity: "Severity",
    affectedArea: "Affected Area",
    recoveryTimeline: "Recovery Timeline",
    observedSymptoms: "Observed Symptoms",
    immediateTreatment: "Immediate Treatment Required",
    chemicalTreatments: "Recommended Chemical Treatments",
    organicTreatment: "Organic Treatment Options",
    fertilizerAdvice: "Fertilizer & Nutrient Recommendations",
    prevention: "Prevention & Future Care",
    downloadReport: "Download Report",
    language: "Language",

    // Analytics Dashboard
    analyticsTitle: "Analytics Dashboard",
    totalScans: "Total Scans",
    uniqueCrops: "Unique Crops",
    avgConfidence: "Avg Confidence",
    diseaseDistribution: "Disease Distribution",
    cropFrequency: "Crop Frequency",
    severityBreakdown: "Severity Breakdown",
    confidenceDistribution: "Confidence Distribution",
    recentScans: "Recent Scans",
    date: "Date",
    action: "Action",
    view: "View",

    // Severity Levels
    severityLow: "Low",
    severityMedium: "Medium",
    severityHigh: "High",

    // Status
    healthy: "Healthy Crop",
    infected: "Disease Detected",

    // Common
    loading: "Loading...",
    error: "Error",
    success: "Success",
    noData: "No data available",
    disclaimer: "Disclaimer",
    disclaimerText:
      "This report is generated by AI-powered analysis and should be used as a guideline. For critical agricultural decisions, please consult agricultural experts, plant pathologists, or local agricultural extension services.",

    // PDF
    pdfTitle: "FasalRakshak - Plant Disease Report",
    reportId: "Report ID",
    scanDate: "Scan Date",
    generatedBy: "Generated by FasalRakshak",
    symptoms: "Symptoms",
    recommendations: "Recommendations",
    treatment: "Treatment",
    chemicalName: "Chemical Name",
    dosage: "Dosage",
    application: "Application Method",
    organicOptions: "Organic Treatment",
    fertilizerRecommendations: "Fertilizer Recommendations",
  },

  hi: {
    // Navigation
    home: "होम",
    scan: "स्कैन",
    dashboard: "डैशबोर्ड",
    analytics: "विश्लेषण",
    aiAssistant: "AI सहायक",
    login: "लॉगिन",
    logout: "लॉगआउट",
    signup: "साइन अप",

    // Home Page
    welcomeTitle: "AI से अपनी फसलों की रक्षा करें",
    welcomeSubtitle: "डीप लर्निंग द्वारा उन्नत पौधा रोग पहचान",
    startScanning: "स्कैनिंग शुरू करें",
    aiAssistantDescription: "पौधों की बीमारियों, उपचार, खेती की तकनीक आदि के बारे में तुरंत जवाब पाएं",
    askAIPlantExpert: "हमारे AI प्लांट विशेषज्ञ से पूछें",
    chatWithAIAssistant: "AI सहायक के साथ चैट करें",
    plantDiseaseHelp: "पौधों की बीमारी में मदद",
    farmingTechniques: "खेती की तकनीक",
    irrigationTips: "सिंचाई युक्तियाँ",
    fertilizerGuide: "उर्वरक गाइड",
    takeClearPhoto: "सटीक रोग पहचान के लिए पौधे की पत्ती या फसल का स्पष्ट फोटो लें",
    uploadImage: "फोटो अपलोड करें",
    clickToBrowse: "ब्राउज़ करने के लिए क्लिक करें या खींचें और छोड़ें",
    chooseFile: "फ़ाइल चुनें",
    takePhoto: "फोटो लें",
    captureLivePhoto: "एक लाइव फोटो कैप्चर करें",
    openCamera: "कैमरा खोलें",
    cameraActive: "कैमरा सक्रिय",
    scanningWithAI: "AI से स्कैन हो रहा है...",
    scanForDisease: "बीमारी के लिए स्कैन करें",
    analyzingPlantImage: "पौधे की छवि का विश्लेषण किया जा रहा है...",
    aiModelProcessing: "AI मॉडल डीप लर्निंग विश्लेषण की प्रक्रिया में है",

    // Results Page
    resultsTitle: "स्कैन परिणाम",
    diseaseDetected: "रोग का पता चला",
    cropName: "फसल का नाम",
    confidence: "विश्वास",
    severity: "गंभीरता",
    affectedArea: "प्रभावित क्षेत्र",
    recoveryTimeline: "ठीक होने की समयावधि",
    observedSymptoms: "देखे गए लक्षण",
    immediateTreatment: "तत्काल उपचार आवश्यक",
    chemicalTreatments: "अनुशंसित रासायनिक उपचार",
    organicTreatment: "जैविक उपचार विकल्प",
    fertilizerAdvice: "उर्वरक एवं पोषक तत्व सिफारिशें",
    prevention: "रोकथाम एवं भविष्य की देखभाल",
    downloadReport: "रिपोर्ट डाउनलोड करें",
    language: "भाषा",

    // Analytics Dashboard
    analyticsTitle: "विश्लेषण डैशबोर्ड",
    totalScans: "कुल स्कैन",
    uniqueCrops: "अद्वितीय फसलें",
    avgConfidence: "औसत विश्वास",
    diseaseDistribution: "रोग वितरण",
    cropFrequency: "फसल आवृत्ति",
    severityBreakdown: "गंभीरता विवरण",
    confidenceDistribution: "विश्वास वितरण",
    recentScans: "हाल के स्कैन",
    date: "तारीख",
    action: "कार्रवाई",
    view: "देखें",

    // Severity Levels
    severityLow: "कम",
    severityMedium: "मध्यम",
    severityHigh: "उच्च",

    // Status
    healthy: "स्वस्थ फसल",
    infected: "रोग का पता चला",

    // Common
    loading: "लोड हो रहा है...",
    error: "त्रुटि",
    success: "सफलता",
    noData: "कोई डेटा उपलब्ध नहीं",
    disclaimer: "अस्वीकरण",
    disclaimerText:
      "यह रिपोर्ट AI आधारित विश्लेषण द्वारा तैयार की गई है। महत्वपूर्ण कृषि निर्णय लेने से पहले कृपया कृषि विशेषज्ञों या स्थानीय कृषि विस्तार सेवाओं से परामर्श करें।",

    // PDF
    pdfTitle: "फसलरक्षक - पौधा रोग रिपोर्ट",
    reportId: "रिपोर्ट आईडी",
    scanDate: "स्कैन तारीख",
    generatedBy: "फसलरक्षक द्वारा निर्मित",
    symptoms: "लक्षण",
    recommendations: "सिफारिशें",
    treatment: "उपचार",
    chemicalName: "रासायनिक नाम",
    dosage: "खुराक",
    application: "आवेदन विधि",
    organicOptions: "जैविक उपचार",
    fertilizerRecommendations: "उर्वरक सिफारिशें",
  },
} as const

/**
 * Translation helper
 * Safe fallback → English → key itself
 */
export function translate<
  K extends keyof typeof translations.en
>(key: K, lang: Language = "en"): string {
  return translations[lang]?.[key] ?? translations.en[key] ?? String(key)
}
